"""Source-level packaging contracts that need no simulator or hardware imports."""

from __future__ import annotations

import ast
import os
import subprocess
import sys
import tomllib
import zipfile
from importlib.metadata import distribution
from pathlib import Path

import pytest

from .conftest import REPOSITORY_ROOT

CONSOLE_ENTRYPOINTS = {
    "libero.create_template": "scripts.create_template:main",
    "libero.download_datasets": "benchmark_scripts.download_libero_datasets:main",
}


@pytest.mark.static
def test_package_data_declares_runtime_assets_and_templates() -> None:
    with (REPOSITORY_ROOT / "pyproject.toml").open("rb") as project_file:
        project = tomllib.load(project_file)

    package_data = project["tool"]["setuptools"]["package-data"]
    assert set(package_data["libero.libero"]) >= {
        "assets/**/*",
        "bddl_files/**/*",
        "init_files/**/*",
    }
    assert "templates/*" in package_data["libero"]
    for relative_path in (
        "libero/libero/assets",
        "libero/libero/bddl_files",
        "libero/libero/init_files",
        "libero/templates/scene_template.xml",
        "libero/templates/problem_class_template.py",
    ):
        assert (REPOSITORY_ROOT / relative_path).exists(), relative_path


@pytest.mark.static
def test_console_entrypoints_are_declared_in_the_packaged_source_tree() -> None:
    with (REPOSITORY_ROOT / "pyproject.toml").open("rb") as project_file:
        project = tomllib.load(project_file)

    assert project["tool"]["setuptools"]["packages"]["find"]["include"] == [
        "benchmark_scripts*",
        "benchmarks*",
        "libero*",
        "scripts*",
    ]
    assert CONSOLE_ENTRYPOINTS.items() <= project["project"]["scripts"].items()

    for entrypoint_name, target in CONSOLE_ENTRYPOINTS.items():
        assert project["project"]["scripts"][entrypoint_name] == target
        module_name, callable_name = target.split(":", maxsplit=1)
        module_path = REPOSITORY_ROOT / Path(*module_name.split(".")).with_suffix(".py")
        module = ast.parse(
            module_path.read_text(encoding="utf-8"), filename=module_path
        )
        assert any(
            isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef))
            and node.name == callable_name
            for node in module.body
        ), f"{target} must target a module-level callable"


@pytest.mark.static
def test_wheel_contains_and_imports_runtime_benchmark_modules(tmp_path: Path) -> None:
    """Runtime's ``benchmarks.ctrl_trace`` import must work outside the source tree."""

    wheel_directory = tmp_path / "wheel"
    build = subprocess.run(
        ["uv", "build", "--wheel", "--out-dir", str(wheel_directory)],
        cwd=REPOSITORY_ROOT,
        capture_output=True,
        check=False,
        text=True,
        timeout=120,
    )
    assert build.returncode == 0, build.stdout + build.stderr
    wheels = tuple(wheel_directory.glob("libero_warp-*.whl"))
    assert len(wheels) == 1
    wheel = wheels[0]

    expected_paths = {
        "benchmarks/__init__.py",
        "benchmarks/ctrl_trace.py",
        "benchmarks/compare_m1_reports.py",
        "benchmarks/benchmark_warp_spike.py",
        "benchmarks/benchmark_official_spike.py",
    }
    with zipfile.ZipFile(wheel) as archive:
        assert expected_paths <= set(archive.namelist())

    environment = _isolated_cli_environment(tmp_path)
    environment["PYTHONPATH"] = str(wheel)
    result = subprocess.run(
        [
            sys.executable,
            "-c",
            (
                "import benchmarks.benchmark_official_spike as official; "
                "import benchmarks.benchmark_warp_spike as warp; "
                "import benchmarks.compare_m1_reports as compare; "
                "import benchmarks.ctrl_trace as trace; "
                "assert '.whl/' in official.__file__; "
                "assert '.whl/' in warp.__file__; "
                "assert '.whl/' in compare.__file__; "
                "assert '.whl/' in trace.__file__"
            ),
        ],
        cwd=tmp_path,
        env=environment,
        capture_output=True,
        check=False,
        text=True,
        timeout=30,
    )
    assert result.returncode == 0, result.stdout + result.stderr


@pytest.mark.static
def test_installed_package_metadata_exposes_required_console_entrypoints() -> None:
    """Check the entry-point metadata generated by the package installation."""

    entrypoints = {
        entrypoint.name: entrypoint.value
        for entrypoint in distribution("libero-warp").entry_points
        if entrypoint.group == "console_scripts"
    }
    assert CONSOLE_ENTRYPOINTS.items() <= entrypoints.items()


@pytest.mark.static
def test_dataset_conversion_module_has_no_legacy_top_level_imports() -> None:
    """``python -m scripts.create_dataset`` must work from an installed wheel."""

    module_path = REPOSITORY_ROOT / "scripts" / "create_dataset.py"
    module = ast.parse(module_path.read_text(encoding="utf-8"), filename=module_path)
    for node in ast.walk(module):
        if isinstance(node, ast.Import):
            assert all(alias.name != "init_path" for alias in node.names)
        if isinstance(node, ast.ImportFrom) and node.module == "libero.libero.envs":
            assert all(alias.name != "*" for alias in node.names)


@pytest.mark.static
def test_retained_packaged_sources_do_not_import_legacy_init_path() -> None:
    """Removed bootstrap code must not remain a runtime dependency in a wheel."""

    retained_roots = (
        REPOSITORY_ROOT / "libero",
        REPOSITORY_ROOT / "scripts",
        REPOSITORY_ROOT / "benchmark_scripts",
    )
    for root in retained_roots:
        for module_path in root.rglob("*.py"):
            module = ast.parse(
                module_path.read_text(encoding="utf-8"), filename=module_path
            )
            for node in module.body:
                if isinstance(node, ast.Import):
                    assert all(alias.name != "init_path" for alias in node.names), (
                        f"{module_path.relative_to(REPOSITORY_ROOT)} imports "
                        "removed init_path"
                    )
                if isinstance(node, ast.ImportFrom):
                    assert node.module != "init_path", (
                        f"{module_path.relative_to(REPOSITORY_ROOT)} imports "
                        "removed init_path"
                    )


@pytest.mark.static
def test_removed_config_copy_tool_is_not_retained() -> None:
    assert not (REPOSITORY_ROOT / "scripts" / "config_copy.py").exists()


def _isolated_cli_environment(tmp_path: Path) -> dict[str, str]:
    config_dir = tmp_path / "libero-config"
    config_dir.mkdir()
    benchmark_root = REPOSITORY_ROOT / "libero" / "libero"
    (config_dir / "config.yaml").write_text(
        "\n".join(
            (
                f"benchmark_root: {benchmark_root}",
                f"bddl_files: {benchmark_root / 'bddl_files'}",
                f"init_states: {benchmark_root / 'init_files'}",
                f"datasets: {tmp_path / 'datasets'}",
                f"assets: {benchmark_root / 'assets'}",
                "",
            )
        ),
        encoding="utf-8",
    )
    environment = os.environ.copy()
    environment.update(
        {
            "HOME": str(tmp_path / "home"),
            "LIBERO_CONFIG_PATH": str(config_dir),
            "MUJOCO_GL": "disable",
        }
    )
    return environment


@pytest.mark.official_integration
@pytest.mark.parametrize(
    "module_name",
    ("benchmark_scripts.download_libero_datasets", "scripts.create_dataset"),
)
def test_retained_dataset_entrypoints_offer_offline_help(
    module_name: str, tmp_path: Path
) -> None:
    """CLI help must not download data, prompt, or use a user's LIBERO config."""

    result = subprocess.run(
        [sys.executable, "-m", module_name, "--help"],
        cwd=REPOSITORY_ROOT,
        env=_isolated_cli_environment(tmp_path),
        capture_output=True,
        check=False,
        text=True,
        timeout=30,
    )
    assert result.returncode == 0, result.stdout + result.stderr


@pytest.mark.static
def test_get_affordance_info_is_an_installed_module_smoke(tmp_path: Path) -> None:
    """Retained utility modules must execute without relying on shell path hacks."""

    result = subprocess.run(
        [sys.executable, "-m", "scripts.get_affordance_info"],
        cwd=REPOSITORY_ROOT,
        env=_isolated_cli_environment(tmp_path),
        capture_output=True,
        check=False,
        text=True,
        timeout=30,
    )
    assert result.returncode == 0, result.stderr
